name: "first-react-workflow"
on: push
jobs:
  first-react:
    runs-on: "windows-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"
        with:
          node-version: "24"
          cache: "npm"
      - name: "install dependencies"
        run: "npm install"
      - name: "make build"
        run: "npm run build"
