name: "first-react-workflow"
on:
  push:
  pull_request:

jobs:
  first-react:
    runs-on: "windows-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v3"

      - name: "setup node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "24"

      - name: "install dependencies"
        run: "npm install"

      - name: "run eslint in app"
        run: "npm run lint"

      - name: "make build"
        run: "npm run build"
